---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/10 17:00
---
require "strict"

print(a)       -- 'a’ is the first appearing variable, so error