---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/11/8 20:49
---

do
    function values(t)
        local i = 0
        return function(stableValue, var)
            print(stableValue, var)
            i = i + 1
            local v = t[i]
            if (v == nil) then
                return nil, nil
            else
                return i, v
            end
        end, "不可变量", "控制变量"
    end

    local t = { 10, 20, 30, 40, 50 }
    for i, v in values(t) do
        print(i, "-----", v)
    end
end