---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/11/13 14:23
---

function my_pairs(t)
    return next, t, nil
end

local l = {
    name = "jiang pengyong",
    [-100] = 100,
    age = 29,
    10, 20, 30
}

print("---------------------")
print("类似 pairs：")
for key, item in my_pairs(l) do
    print(key, "-->", item)
end

print("---------------------")
print("pairs：")
for key, item in pairs(l) do
    print(key, "-->", item)
end

print("---------------------")
print("next：")
print(next)
print("判断表是否为空", next({}))
print("调用两次 nil 的 next：", next(l))
print("调用两次 nil 的 next：", next(l))