---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/11/1 22:25
---

--- 运行预编译文件的方式：
--- 第一种：lua 预编译的文件.lc

print("----------------------------")
print("第二种：loadfile 运行预编译文件")
do
    print("----------------------------")
    print("loadfile 加载：")
    local fun, error = loadfile("/Users/jiangpengyong/Desktop/code/Lua/lua_study_2022/10 编译、执行和错误/预编译/预编译的文件1.lc")
    print(fun, error)
    fun()

    print("----------------------------")
    print("dofile 加载：")
    dofile("/Users/jiangpengyong/Desktop/code/Lua/lua_study_2022/10 编译、执行和错误/预编译/预编译的文件1.lc")

    print("----------------------------")
    print("load 加载：")
    local lines = io.lines("/Users/jiangpengyong/Desktop/code/Lua/lua_study_2022/10 编译、执行和错误/预编译/预编译的文件1.lc", 1024)
    local l = load(lines)
    l()

end