---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/11/1 22:25
---

--- 运行预编译文件的方式：
--- 第一种：lua 预编译的文件.lc

print("----------------------------")
print("第二种：loadfile 运行预编译文件")
do
    print("----------------------------")
    print("loadfile 加载：")

    local currentPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")
    local fun, error = loadfile(currentPath .. "预编译的文件.lc", "b")
    print(fun, error)
    fun()

    print("----------------------------")
    print("dofile 加载：")
    dofile(currentPath .. "预编译的文件.lc", "b")

    print("----------------------------")
    print("load 加载：")
    local lines = io.lines(currentPath .. "预编译的文件.lc", 1024)
    local l = load(lines)
    l()
end