---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/11/1 22:22
---

print("Hello, jiang pengyong.")

local name = "江澎涌"
local age = 29

print(name, age)

