---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/11/1 22:32
---

--- 预编译文件的方式：
--- 第一种：luac -o 预编译的文件.lc 预编译的文件.lua

--- 第二种：读取文件后，以二进制方式
local currentPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")
do
    p = loadfile(currentPath .. "/预编译的文件.lua")
    f = io.open(currentPath .. "/预编译的文件1.lc", "wb")
    --- string.dump 入参一个 Lua 函数，返回值是传入函数对应的字符串的预编译代码
    --- 已被正确格式化，可由 Lua 语言直接加载
    f:write(string.dump(p, true))
    f:close()
end