---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/11 10:27
---

print("---------------")
print("函数变量：")
do
    -- 将 a.p 指向 print 函数
    a = { p = print }
    -- 使用 a.p 函数
    a.p("jiangpengyong")
    -- 将 print 指向 math.sin，但不会影响原有的 a.p
    print = math.sin
    a.p(print(1))
    -- 将 math.sin 指向 a.p
    local sin = math.sin
    math.sin = a.p
    math.sin(10, 20)

    math.sin = sin
    print = a.p
end

print("---------------")
print("匿名函数：")
do
    foo = function(x)
        return x * x
    end

    print(foo(2))
    print("type(foo)", type(foo))

    function foo1()
        print("Foo1 called.")
    end
    foo1()
    print("type(foo1)", type(foo1))
    foo1 = nil
    --foo1()    -- attempt to call a nil value (global 'foo1')
    print("type(foo1)", type(foo1))
end

print("---------------")
print("排序：")
do
    t = {
        { name = "xiao peng you", age = 20 },
        { name = "zinc", age = 27 },
        { name = "jiang peng yong", age = 28 },
    }
    table.sort(t, function(a, b)
        return #a.name > #b.name
    end)
    for i, v in ipairs(t) do
        print(i, "-->", v.name, "--", v.age)
    end
end

print("---------------")
print("高阶函数：")
do
    -- 导数
    function derivative(f, delta)
        delta = delta or 1e-4
        return function(x)
            return (f(x + delta) - f(x)) / delta
        end
    end
    c = derivative(math.sin)
    print(math.cos(5.2), c(5.2))
end

print("---------------")
print("定义 table 函数，三种方式：")
do
    -- 第一种
    Lib1 = {}
    Lib1.add = function(a, b)
        return a + b
    end
    Lib1.reduce = function(a, b)
        return a - b
    end
    print("Lib1", Lib1.add(10, 2), Lib1.reduce(2, 3))

    -- 第二种
    Lib2 = {
        add = function(a, b)
            return a + b;
        end,
        reduce = function(a, b)
            return a - b;
        end
    }
    print("Lib2", Lib2.add(10, 2), Lib2.reduce(2, 3))

    -- 第三种
    Lib3 = {}
    function Lib3.add(a, b)
        return a + b
    end
    function Lib3.reduce(a, b)
        return a - b
    end
    print("Lib3", Lib3.add(10, 2), Lib3.reduce(2, 3))
end

print("---------------")
print("局部函数：")
do
    -- 局部函数，几种方式
    local function fact1(n)
        if n == 0 then
            return 1
        end
        return n * fact1(n - 1)
    end
    print(fact1(10))

    -- 局部函数
    -- 这样使用会有问题
    --local fact2 = function(n)
    --    if n == 0 then
    --        return 1
    --    end
    --    -- 因为 Lua 语言编译函数体中的 fact2(n-1) 调用时，局部的 fact2 尚未定义。
    --    return n * fact2(n - 1)    -- attempt to call a nil value (global 'fact2')
    --end
    --print(fact2(10))

    -- 最开始的写法其实 Lua 会帮忙编译为以下
    local fact3
    fact3 = function(n)
        if n == 0 then
            return 1
        end
        return n * fact3(n - 1)
    end
    print(fact3(10))

end

print("---------------")
print("作用域逃逸：")
do
    function newCounter()
        local count = 0
        return function()
            count = count + 1
            return count
        end
    end

    local c1 = newCounter()
    print("c1", c1())
    print("c1", c1())

    local c2 = newCounter()
    print("c2", c2())
    print("c1", c1())
    print("c2", c2())
    print("c2", c2())
end

print("---------------")
print("更换预定义函数：")
print("更换前，使用弧度制", math.sin(math.rad(90)))
do
    local oldSin = math.sin
    math.sin = function(value)
        return oldSin(value * (math.pi / 180))
    end
end
print("更换后，使用角度", math.sin(90))