---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/17 10:32
---

print("==================================")
print("进入模块")
print("模块入参：", ...)

-- 这里没有使用 local ， 则会让外部调用 require 的文件也导入了该属性，其实就是全局
local name = "江澎涌"

local foo = function()
    print("foo", name)
end

print("即将出模块")
print("==================================")

-- 第一种返回，使用 return 进行返回值
--return {
--    name = name,
--    foo = foo
--}

-- 第二种返回，将返回值直接设置为 loaded 的值，键是就是 module 的名
package.loaded[...] = {
    name = name,
    foo = foo
}
