---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/17 10:32
---

print("------------------------")
print("获取运行的路径是相对于运行环境")
print("pwd:", os.execute("pwd"))

print("------------------------")
print("配置搜索路径")
local currentPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")
-- 在设置环境变量的时候，使用 ";;" 会被替换成默认路径
package.path = package.path .. ";" .. currentPath .. "?.lua"
print("搜索路径：", package.path)

print("------------------------")
print("加载模块：")
do
    local userInfo = require("被加载的模块")
    if userInfo == nil then
        print("load module failure")
    end
    print(userInfo.name)
    userInfo.foo()
    print(name)
end

print("------------------------")
print("重复加载同一模块：")
do
    require("被加载的模块")
end

print("------------------------")
print("删除模块，再加载：")
do
    package.loaded["被加载的模块"] = nil
    require("被加载的模块")
end

print("------------------------")
do
    local module = require("被加载没有返回值的模块")
    print(module)

    local reloadModule = require("被加载没有返回值的模块")
    print(reloadModule)
end



