---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/16 21:20
---

do
    local name = {}
    local f = xpcall(function()
        if (type(name) ~= "string") then
            error("string expected")
        end
    end, function()
        print("xpcall")
        --debug.debug()
        debug.traceback()
    end)
end