---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/4 2:32 PM
---

N = 8

-- 检查 （n，c） 是否会被攻击
function isPlaceOk(a, n, c)
    for i = 1, n - 1 do
        if (a[i] == c) or
                (a[i] - i == c - n) or
                (a[i] + i == c + n) then
            return false
        end
    end
    return true
end

-- 打印棋盘
function printSolution(a)
    for i = 1, N do
        for j = 1, N do
            io.write(a[i] == j and "X" or "-", " ")
        end
        io.write("\n")
    end
    io.write("\n")
end

function addQueen(a, n)
    if n > N then
        printSolution(a)
    else
        for c = 1, N do
            if isPlaceOk(a, n, c) then
                a[n] = c
                addQueen(a, n + 1)
            end
        end
    end
end

addQueen({}, 1)