---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/10 16:39
---

-- 这里会无限循环
--x = 10
--local i = 1             -- 对于代码段（所在文件）来说是局部的
--while x <= 10 do        -- 此处 x 使用的是全局变量
--    local x = i * 2     -- 此处 x 对于循环体来说是局部的
--    print(x)            --> 2,4,6,8 ..
--    i = i + 1
--end

do
    local name = "jiang peng yong"
    print(name)
end
print(name)

age = 20
do
    local age = age
    print(age)
    age = 10
    print(age)
end
print(age)

do
    a = { "one", "two", "three" }
    for i, v in ipairs(a) do
        print(i, v)
    end
    for i, v in pairs(a) do
        print(i, v)
    end
end

do
    :: s1 ::
    do
        local c = io.read("l")
        if (c == '0') then
            goto s2
        elseif c == 'nil' then
            print("ok")
            return
        else
            goto s1
        end
    end

    :: s2 ::
    do
        local c = io.read("l")
        if (c == '0') then
            goto s1
        elseif c == 'nil' then
            print("not ok")
        else
            goto s2
        end
    end

    goto s1
end
