---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/9/25 13:12
---

print("-----------")
--- name 没有声明过，所以会为 nil，表什么当前什么都没有
print(name)

print("-----------")
local name = "江澎涌"
print(name)

print("-----------")
--- 将 name 置为 nil 进行删除
name = nil
print(name)

--- 创建一个表
---   key    |      value
--- "name"   |  "jiangpengyong"
print("-----------")
local table = { name = "jiangpengyong" }
print(table["name"])
table["name"] = nil
print(table["name"])

print("-----------")
print("类型")
print(type(X))

--- 因为这里的 type(X) 是 string 类型，所以不等 nil
print(type(X)==nil)

--- 需要使用 "nil" 进行比较
print(type(X)=="nil")

--- 使用这样也是可以
print(X == nill)