---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/11/5 18:57
---

print("--------------------------")
print("package.searchers 搜索器：")
do
    --- 第一个是预加载搜索器
    --- 第二个是 Lua 搜索器
    --- 第三个是 C 搜索器
    --- 第四个是针对于 C 库子模块搜索器
    for k, v in pairs(package.searchers) do
        print(k, "-->", v)
    end
end

print("--------------------------")
print("设置搜索器：")
do
    package.searchers[#package.searchers + 1] = function(moduleName)
        print("moduleName: ", moduleName)
        return loadfile("/Users/jiangpengyong/Desktop/code/Lua/lua_study_2022/11 模块和包/搜索器/被搜索器加载的文件.lua")
    end
    local module = require("不能存在的模块")
    print(module, module.name)

    local module1 = require("不能存在的模块2")
    print(module1, module1.name)

    print("加载已存在模块：")
    local module2 = require("不能存在的模块2")
    print(module2, module2.name)
end

print("--------------------------")
print("package.searchers 搜索器：")
do
    for k, v in pairs(package.searchers) do
        print(k, "-->", v)
    end
end