---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/8 22:32
---

rootPath = "/Users/jiangpengyong/Desktop/code/Lua/lua_study_2022/io/"

-- 输出
print("io.write")
io.output(rootPath .. "jiangpengyong.txt")
io.write("jiang", "peng", "yong", "\n")
io.write("jiang" .. "peng" .. "yong" .. "\n")

-- 格式输出
print("格式输出")
io.write("sin(3) = ", math.sin(3), "\n")
-- 如果需要格式化，则需要调用 string.format
io.write(string.format("sin(3) = %.4f", math.sin(3)), "\n")

-- 输入
io.input(rootPath .. "一件小事.txt")
line = io.read("l")
print(line)
print("")
article = io.read("a")
print(article)
-- 文本替换
change = string.gsub(article, "我", "*")
print(change)

print("")
io.input(rootPath .. "一件小事.txt")
article = io.read("all")
print(article)
print("")
-- 将所有非 ASCII 字符串替换为编码 =xx
print(string.gsub(article, "([\128-\255=])", function(c)
    return string.format("=%02X", string.byte(c))
end))
-- 已经到输入流末尾，进行读取
print("io.read(\"a\"): ", io.read("a"))
print("io.read(\"l\"): ", io.read("l"))
print("io.read(\"L\"): ", io.read("L"))
print("io.read(\"n\"): ", io.read("n"))
print("io.read(9): ", io.read(9))

-- 遍历输入流
-- 通过 io.read("L") 进行读取遍历
io.input(rootPath .. "一件小事.txt")
io.output(rootPath .. "一件小事-copyByReadLine")
for count = 1, math.huge do
    local line = io.read("L")
    if line == nil then
        break
    end
    io.write(string.format("%6d  ", count), line)
end
-- 通过 io.lines() 进行读取遍历
-- do end 只是限定一个作用域
io.input(rootPath .. "一件小事.txt")
io.output(rootPath .. "一件小事-copyByLines")
do
    local count = 0
    for line in io.lines() do
        count = count + 1
        io.write(string.format("%6d  ", count), line, "\n")
    end
end

do
    io.input(rootPath .. "一件小事.txt")
    io.output(rootPath .. "一件小事-copyForSort")
    local lines = {}
    local count = 0
    for line in io.lines() do
        count = count + 1
        -- 因为 table 是从 1 开始的
        lines[#lines + 1] = line
    end
    table.sort(lines)
    for _, v in ipairs(lines) do
        io.write(v, "\n")
    end
end

-- 使用 io.read(num) 进行拷贝
do
    io.input(rootPath .. "一件小事.txt")
    io.output(rootPath .. "一件小事-copyByReadNum")
    while true do
        local block = io.read(2 ^ 13) -- 8k
        if block == nil then
            break
        end
        io.write(block)
    end
end

do
    io.input(rootPath .. "number.txt")
    while true do
        n1, n2, n3 = io.read("n", "n", "n")
        print(n1, n2, n3)
        if n3 == nil then
            break
        end
    end
end

-- io.open
do
    print(io.open("notExistFile.txt", "r"))
    --local file = assert(io.open("notExistFile.txt", "r"))
end
do
    local file = io.open(rootPath .. "一件小事.txt", "r")
    -- 需要使用 冒号
    local t = file:read("a")
    file:close()
    print(t)
end
do
    -- 预设的三个流句柄：
    --readNum = io.stdin:read("n")
    --print("num", readNum)
    --io.stdout:write("jiang", "peng", "yong!!!", "\n")
    --io.stderr:write("error message.")
end

-- 切换输入、输出流
do
    print("")
    print("切换输入、输出流")
    io.input(rootPath .. "一件小事.txt", "r")
    -- 获取当前流局柄
    article1 = io.input()
    -- 重新打开一个文件，读取内容，关闭
    io.input(rootPath .. "names.txt", "r")
    print(io.read("l"))
    io.input():close()
    -- 切换为 article1
    io.input(article1)
    print(io.read("l"))
    -- 关闭 article1
    io.input():close()
end
