---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/20 7:45 PM
---

package.path = package.path .. ";/Users/jiangpengyong/Desktop/study/lua_study_2022/15 环境/模块隔离/?.lua"
local M = require("module")

print("a", a)
print("M.a", M.a)
print("b", b)
print("M.b", M.b)