---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/20 7:45 PM
---

local currentPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")
package.path = package.path .. ";" .. currentPath .. "?.lua"
local M = require("module")

print("a", a)
print("M.a", M.a)
print("b", b)
print("M.b", M.b)