---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/16 14:31
---

do
    local function Set(list)
        local set = {}
        for _, l in ipairs(list) do
            set[l] = true
        end
        return set
    end

    reserved = Set { "while", "end", "function", "local" }
    for i, v in pairs(reserved) do
        print(i, "==>", v)
    end
end

do
    print("")
    local s = [[_while]]
    local ids = {}
    for w in string.gmatch(s, "[%a_][%w_]*") do
        if not reserved[w] then
            ids[w] = true
        end
    end

    for w in pairs(ids) do
        print(w)
    end
end
