---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/23 16:47
---

print("=========================================")
print("遍历局部变量（栈层次）：")
do
    local outerParam = "外部局部变量"
    globalParam = "全局变量"
    local function foo(funParamA, funParamB, ...)
        local localParamX
        do
            local localParamC = funParamA - funParamB
        end
        local localParamA = 1
        print("------------------------------------")
        print("遍历变量:")
        -- for 循环只是为了临时模拟临时变量，所以一次循环就退出
        for i = 1, 2 do
            while true do
                local name, value = debug.getlocal(1, localParamA)
                if not name then
                    break
                end
                print(name, "---", value)
                localParamA = localParamA + 1
            end
            break
        end

        print("------------------------------------")
        print("遍历可变参数:")
        localParamA = -1
        while true do
            local name, value = debug.getlocal(1, localParamA)
            if not name then
                break
            end
            print(name, "---", value)
            localParamA = localParamA - 1
        end
    end
    foo(1, 200, "jiang", "pengyong")
end

print("=========================================")
print("遍历局部变量（函数）：")
do
    local function foo(funParamA, funParamB, ...)
        local localParamX = "江澎涌"
    end
    for i = 1, math.huge do
        local name, value = debug.getlocal(foo, i)
        if not name then
            break
        end
        print(name, "---", value)
    end
end

print("=========================================")
print("设置局部变量")
do
    function showLocalParam()
        for i = 1, math.huge do
            local name, value = debug.getlocal(2, i)
            if not name then
                break
            end
            print(name, "---", value)
        end
    end

    local name = "jiang pengyong"
    local age = 29
    do
        local name = "江澎涌"

        print("-------------------------------------")
        print("设置前：")
        showLocalParam()

        print("-------------------------------------")
        -- 修改的是外部的 name ，而非内部的 name
        print("debug.setlocal",debug.setlocal(1, 1, "jiang"))

        print("-------------------------------------")
        print("设置后：")
        showLocalParam()
    end
end