---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/23 22:16
---

co = coroutine.create(function()
    local x = 10
    coroutine.yield(x)
    error("coroutine error............")
end)

print("运行返回", coroutine.resume(co))
print("打应栈", debug.traceback(co))

print("运行返回", coroutine.resume(co))
print("打应栈", debug.traceback(co))

print("获取局部变量", debug.getlocal(co, 1, 1))