---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/23 16:27
---

print("==============================================")
print("获取普通方法的 getinfo ：")
do
    function foo(a, b, ...)
        print("江澎涌")
    end
    local info = debug.getinfo(foo)
    for k, v in pairs(info) do
        print(k, "---", v)
    end
end

print("==============================================")
print("使用数值调用 getinfo ：")
do
    foo1 = function(...)
        local table = debug.getinfo(1)
        for k, v in pairs(table) do
            print(k, "---", v)
        end
    end
    foo1()
end

print("==============================================")
print("模仿 debug.traceback ：")
do
    local function traceback()
        -- 0 是 debug.getinfo 自身
        -- 1 是调用 debug.getinfo 的代码
        -- 2 是调用 traceback 的代码
        for level = 0, math.huge do
            local info = debug.getinfo(level, "Sl")
            if not info then
                break
            end
            if info.what == "C" then
                print(string.format("%d\tC function", level))
            else
                print(string.format("%d\t[%s]:%d", level, info.short_src, info.currentline))
            end
        end
    end
    traceback()
end

print("==============================================")
print("调用 debug.traceback ：")
do
    print("没有参数")
    local function foo1()
        print(debug.traceback())
    end
    foo1()

    print("携带 message（字符串）")
    local function foo2()
        print(debug.traceback("track back message."))
    end
    foo2()

    print("携带 message（非字符串）")
    local function foo3()
        print(debug.traceback({}))
    end
    foo3()

    print("携带 message（非字符串）且携带 level ")
    local function foo4()
        --print(debug.traceback("track back message.", 0))
        --print(debug.traceback("track back message.", 1))
        print(debug.traceback("track back message.", 2))
        --print(debug.traceback(nil, 2))
    end
    foo4()
end
