---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/24 07:44
---

function foo()
    print("jiang pengyong")
end

local currentPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")
local f = assert(loadfile(currentPath .. "调优(统计调用次数).lua"))
f()
debug.sethook(hook, "c")
foo()
debug.sethook()

--for func, count in pairs(Counters) do
--    print(getName(func), count)
--end