---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/24 07:39
---

print("=========================================================")
print("统计调用次数：")
do
    local Counters = {}
    local Names = {}

    local function hook()
        local f = debug.getinfo(2, "f").func
        local n = debug.getinfo(2, "n").name
        local count = Counters[f]
        if count == nil then
            print(f, n)
            Counters[f] = 1
            Names[f] = debug.getinfo(2, "Sn")
        else
            Counters[f] = count + 1
        end
    end

    local function getName(func)
        local n = Names[func]
        if n.what == "C" then
            return n.name
        end
        local lc = string.format("[%s]:%d", n.short_src, n.linedefined)
        if n.what ~= "main" and n.namewhat ~= "" then
            return string.format("%s (%s)", ls, n.name)
        else
            return lc
        end
    end

    local currentPath = debug.getinfo(1,"S").source:sub(2):match("(.*/)")
    local f = assert(loadfile(currentPath.."被加载的Lua.lua"))
    debug.sethook(hook, "c")
    f()
    --f()
    --f()
    debug.sethook()

    print("--------------------------------")
    print("输出格式：")
    for func, count in pairs(Counters) do
        print(getName(func), count)
    end

    print("--------------------------------")
    print("Counters：")
    print(Counters[debug.getinfo])
    for k, v in pairs(Counters) do
        print(k, "----", v)
    end
    print("--------------------------------")
    print("Names:")
    for k, v in pairs(Names) do
        print("-------------------", k, "-------------------")
        for i, v in pairs(v) do
            print(i, "------", v)
        end
    end
end