---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/22 08:56
---

do
    -- 创建协程
    co1 = coroutine.create(function()
        print("Hello world.")
    end)
    print("status(coroutine)", coroutine.status(co1))
    print("type(coroutine)", type(co1))
    coroutine.resume(co1)
    print("status(coroutine)", coroutine.status(co1))
end

do
    co2 = coroutine.create(function()
        for i = 1, 10 do
            coroutine.yield(i)
        end
    end)
end