---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/24 08:55
---

local socket = require "socket"
host = "www.lua.org"
file = "/manual/5.4/manual.html"

c = assert(socket.connect(host, 80))

local request = string.format("GET %s HTTP/1.0\r\nhost:%s\r\n\r\n", file, host)
c:send(request)

repeat
    local s, status, partial = c:receive(2 ^ 10)
    io.write(s or partail)
until status == "closed"

c:close()