---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/23 12:29
---

function receive(prod)
    local status, value = coroutine.resume(prod)
    return value
end

function send(x)
    coroutine.yield(x)
end

function producer()
    return coroutine.create(function()
        local x = 1
        while true do
            x = x + 1
            send(x)
        end
    end)
end

-- 衔接了两方的数据
function filter(prod)
    return coroutine.create(function()
        for line = 1, math.huge do
            local x = receive(prod)
            x = string.format("%5d --- %s", line, x)
            send(x)
        end
    end)
end

function consumer(prod)
    for i = 1, 1000 do
        local x = receive(prod)
        print(x)
    end
end

consumer(filter(producer()))