---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/11/18 08:03
---

-- 设置使用 rawset 绕开元表机制
-- 而且此设置要在设置元表之前，否则 declare 的设置也会被认为是对全局表的设置
function declare(name, initial)
    rawset(_G, name, initial or false)
end

setmetatable(_G, {
    -- 仅能在 "主代码(main)" 和 "C 函数" 中赋值全局
    __newindex = function(t, n, v)
        -- 获取代码段的位置
        local w = debug.getinfo(2, "S").what
        print(w)
        -- 仅能在 "主代码(main)" 和 "C 函数" 中赋值全局
        if w ~= "main" and w ~= "C" then
            error(string.format("attempt to write to undeclared variable %s", n), 2)
        end
        rawset(t, n, v)
    end,
    -- 不能创建全局变量
    --__newindex = function(t, n, v)
    --    error(string.format("attempt to write to undeclared variable %s", n), 2)
    --end,
    __index = function(_, n)
        error(string.format("attempt to read undeclared variable %s", n), 2)
    end
})

name = "jiang"
print(name)

declare("age", 100)
print(age)

-- 判断一个元素是否初始化
if rawget(_G, "b") == nil then
    print("b 未初始化")
end
