---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/20 08:25
---

do
    -- 通过将 _ENV 设置为 nil ， 从而打断了与全局关系
    local print, sin = print, math.sin
    -- attempt to index a nil value (upvalue '_ENV')
    --_ENV = nil
    print(13)
    print(sin(13))
    print(math.cos(13))
end

do
    a = 1000
    print("a", a)
    print("_ENV.a", _ENV.a)
    -- attempt to index a nil value (upvalue '_ENV')
    --_ENV = nil
    print("_G.a", _G.a)
end

_ENV = { _G = _G }
b = 10
_G.print("b", b)
_G.print("_ENV.b", _ENV.b)
_G.print("_G.b", _G.b)