---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/20 8:04 PM
---

env = {}

loadfile("/Users/jiangpengyong/Desktop/study/lua/lua_study_2022/环境/config.lua", "t", env)()

print(env.width, env.height)

f = load("b = 10; return a;")
env = {a = 20}
debug.setupvalue(f, 1, env)
print(f())
print(env.b)