---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/20 8:18 PM
---

env = {}
f = load([[
    _ENV = ...;
    a = 100;
    b = 10;
]])
f(env)
print(env.a, env.b)
print(a, b)
