---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/20 7:46 PM
---

local print = print
M = {}
_ENV = M

a = "江澎涌"
b = 10

print("module", a)
print("module", b)