---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/19 7:44 PM
---

function getField(f)
    local v = _G
    for w in string.gmatch(f, "[%a_][%w_]*") do
        v = v[w]
    end
    return v
end

function setField(f, v)
    local t = _G
    for w, d in string.gmatch(f, "([%a_][%w_]*)(%.?)") do
        if d == "." then
            t[w] = t[w] or {}
            t = t[w]
        else
            t[w] = v
        end
    end
end

function showGlobal()
    for k, v in pairs(_G) do
        print(k, "---", v)
    end
end

setField("t.x.y", 10)
print(t.x.y)
print(getField("t.x.y"))

showGlobal()