---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/20 7:45 PM
---

--package.path = package.path .. ";/Users/jiangpengyong/Desktop/code/Lua/lua_study_2022/模块和包/?.lua"
package.path = package.path .. ";/Users/jiangpengyong/Desktop/study/lua/lua_study_2022/环境/?.lua"
require("module")

print("a", a)
print("M.a", M.a)
print("b", b)
print("M.b", M.b)

c = "小朋友"
print("c", c)