---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/24 07:22
---

x = "jiang pengyong"

do
    -- 开始新的行时，会调用 print
    debug.sethook(print, "l")

    print("江澎涌")
    print("小朋友")
    debug.sethook()
end

do
    print("")
    function trace(event, line)
        local s = debug.getinfo(2).short_src
        print(s, ":", line)
    end
    debug.sethook(trace, "l")
    print("江澎涌")
    print("小朋友")
    debug.sethook()
end

do
    function debug1()
        while true do
            io.write("debug> ")
            local line = io.read()
            if line == "cont" then
                break
            end
            assert(load(line))()
        end
    end
end

debug.debug()