---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/23 16:47
---

do
    function foo(a, b)
        local x
        do
            local c = a - b
        end
        local a = 1
        while true do
            local name, value = debug.getlocal(1, a)
            if not name then
                break
            end
            print(name, "---", value)
            a = a + 1
        end

        print(debug.getlocal(1,1))
        debug.setlocal(1, 1, 100)
        print(debug.getlocal(1,1))

    end

    foo(1, 200)
end