---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/23 17:02
---

function getVarValue(name, level, isEnv)
    local value
    local found = false

    -- 取局部变量
    level = (level or 1) + 1
    for i = 1, math.huge do
        local n, v = debug.getlocal(level, i)
        if not n then
            break
        end
        if n == name then
            value = v
            found = true
        end
    end
    if found then
        return "local", value
    end

    -- 取闭包变量
    local func = debug.getinfo(level, "f").func
    for i = 1, math.huge do
        local n, v = debug.getupvalue(func, i)
        if not n then
            break
        end
        if n == name then
            print("value", n, v)
            return "upValue", v
        end
    end
    if isEnv then
        return "noEnv"
    end

    -- 找上一层的 _ENV
    local g, env = getVarValue("_ENV", level, true)
    print("global variable", g, env)
    if env then
        return "global", env[name]
    else
        return "noEnv"
    end
end

a = "江澎涌"
print(getVarValue("a"))
local a = 4
do
    print(getVarValue("a"))
end
