---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/23 16:27
---

do
    local function foo()
        print("江澎涌")
    end
    print("foo", foo)
    local info = debug.getinfo(foo)
    print(type(info))
    for k, v in pairs(info) do
        print(k, "---", v)
    end
end

do
    print("")
    local foo1 = function(...)
        local table = debug.getinfo(1)
        for k, v in pairs(table) do
            print(k, "---", v)
        end
    end
    foo1()
end

do
    print("")
    function foo2()
        print(debug.traceback())
    end
    foo2()
end
