---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/23 22:16
---

co = coroutine.create(function()
    local x = 10
    coroutine.yield(x)
    error("coroutine error............")
end)

print(coroutine.resume(co))
print(debug.traceback(co))

print(coroutine.resume(co))
print(debug.traceback(co))

print(debug.getlocal(co, 1, 1))