---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2023/9/1 10:26
---

-- 获取当前 lua 的文件夹路径
local currentPath = debug.getinfo(1,"S").source:sub(2):match("(.*/)")

package.path = package.path .. ";"..currentPath.."../?.lua"
local module = require("一个合理的模块")
print(module.name)
module.showInfo()

require("module.sub")

print("--------------------------")
print("package.loaded 已经加载的模块：")
do
    for k, item in pairs(package.loaded) do
        print(k, "包含的属性：")
        if type(item) == "table" then
            for key, value in pairs(item) do
                print(key, "---", value)
            end
        else
            print(key, "---", item)
        end
    end
end