---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2023/9/1 13:51
---

print("package.preload：")

local function showLoadedModule()
    for path, package in pairs(package.loaded) do
        print("----- 模块【" .. path .. "】包含的属性：-----")
        if type(package) == "table" then
            for key, value in pairs(package) do
                print(key, "---", value)
            end
        else
            print(path, "---", package)
        end
        print("--------------------------------")
    end
end

package.preload["testModule"] = function(name, source)
    print("加载函数", name, source)
    return { name = "江澎涌" }
end

do
    for k, v in pairs(package.preload) do
        print(k, "-->", v)
    end
end

--showLoadedModule()

--- 会调用到 preload 的加载函数，加载完会将 testModule 的返回值放入到 loaded 中
require("testModule")

--showLoadedModule()