---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/10/28 22:53
---

print("==================================")
print("进入模块")
print("模块入参：", ...)

return { name = "江澎涌" }
