---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/17 10:32
---

-- 运行的路径是相对于运行环境
print("pwd:", os.execute("pwd"))

-- ;; 会被替换成默认路径
package.path = package.path .. ";/Users/jiangpengyong/Desktop/code/Lua/lua_study_2022/模块和包/?.lua"
userInfo = require("test_module")
if userInfo == nil then
    print("load module failure")
end
print(userInfo.name)
userInfo.foo()
print(name)

print("")
print("package.path")
print(package.path)
