---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/17 10:03
---

path = "/Users/jiangpengyong/Desktop/code/Lua/lua_study_2022/模块和包/?.lua"
print(package.searchpath("模块和包", path))
print(package.searchpath("模块", path))

print("")
print("package.path", package.path)
print("package.cpath", package.cpath)

print("")
print("package.loaded")
for k, table in pairs(package.loaded) do
    print(k)
    for key, value in pairs(table) do
        print(key, "---", value)
    end
end

print("")
print("package.searchers")
for i, v in pairs(package.searchers) do
    print(i, "=====》", v)
end