---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/17 20:41
---

t = {}
print(getmetatable(t))

t1 = {}
setmetatable(t, t1)
print(getmetatable(t) == t1)

print(getmetatable("jiang"))
print(getmetatable("pengyong"))
print(getmetatable(10))
print(getmetatable(math.sin))

-- __metatable 设置
t2 = { c = 1 }
t2.__metatable = { a = 1 }
s1 = {}
setmetatable(s1, t2)
print(getmetatable(s1)["a"])
-- cannot change a protected metatable
print(setmetatable(s1, {}))