---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/20 9:32 PM
---

do
    local function setDefault(table, default)
        local mt = { __index = function()
            return default
        end }
        setmetatable(table, mt)
    end

    local t = { x = 10, y = "江" }
    print(t.x, t.y, t.z)
    setDefault(t, "涌")
    print(t.x, t.y, t.z)
end

do
    local mt = { __index = function(table)
        return table.___
    end }
    local function setDefault(table, default)
        table.___ = default
        setmetatable(table, mt)
    end

    local t = { x = 10, y = "江" }
    print(t.x, t.y, t.z)
    setDefault(t, "涌")
    print(t.x, t.y, t.z)
end

do
    local key = {}
    local mt = { __index = function(table)
        return table[key]
    end }
    local function setDefault(table, default)
        table[key] = default
        setmetatable(table, mt)
    end

    local t = { x = 10, y = "江" }
    print(t.x, t.y, t.z)
    setDefault(t, "涌")
    print(t.x, t.y, t.z)
end