---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2023/9/1 15:10
---

print("package.searchpath: ")

local currentPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")
local path = "?.lua;"..currentPath .. "?.lua"

print(package.searchpath("module!sub", path, "!", "@"))
print(package.searchpath("module.sub", path))
print(package.searchpath("模块", path))
