---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/11/5 19:44
---

local man = {}

function man.sayHello()
    print("Hello.")
end

man.name = "jiang pengyong"

local age = 29
man.age = age

local function showInfo()
    print("My name is " .. man.name .. "." ..
            "I'm " .. man.age .. " years old.")
end
man.showInfo = showInfo

return man