---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2023/8/25 08:23
---

-- 两种书写方式都可以使用
local math = require "math"
--local math = require("math")

-- sin 使用的是弧度，不是角度
print(math.sin(3.14))

-- 引用模块中的某个函数
-- 等同于 require("math").sin
-- 此时 require("math") 获取到了引入表，`.sin` 即从表中获取了对应的值 value ，此时为一个函数
local sin = require "math".sin
print(sin(3.14))