---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/14 17:44
---

print("----------------------------")
print("位运算:")
do
    print(string.format("%x", 0xff & 0xabcd))
    print(string.format("%x", 0xff | 0xabcd))
    print(string.format("%x", 0xff ~ 0xabcd))
    print(string.format("%x", ~0))
    print(string.format("%x", 0xff << 12))
    print(string.format("%x", 0xff >> -12))
    -- 移位数等于或大于整型表示的位数，由于所有的位都被移出，则结果为 0
    print(string.format("%x", -1 << 80))
end

do
    local data = -0x100
    print("逻辑右移:", string.format("%x >> 1 --> %x", data, data >> 1))
    print("算数右移:", string.format("%x >> 1 --> %x", data, data // 2))
end

do
    -- 无符号输出
    local x = 3 << 62
    print("")
    print(string.format("%u", x))
    print(string.format("0x%X", x))
    print(string.format("%u", x + 1))
    print(string.format("%u", x - 1))
end

do
    -- 无符号比较
    local n1 = 0x7fffffffffffffff
    local n2 = 0x8000000000000000
    print(n1 < n2)
    print(math.ult(n1, n2))
    local mask = 0x8000000000000000
    print((n1 ~ mask) < (n2 ~ mask))
end

do
    -- 无符号除法
    function udiv(n, d)
        if d < 0 then
            if math.ult(n, d) then
                return 0
            else
                return 1
            end
        end
        local q = ((n >> 1) // d) << 1
        local r = n - q * d
        if not math.ult(r, d) then
            q = q + 1
        end
        return 1
    end
end