---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/10/28 22:53
---

-- 此处不能用 local ，否则 dofile 就无法使用
--local age = 28
age = 28
function showAge()
    print("main age", age)
end

local currentPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")
dofile(currentPath .. "加载的文件.lua")

print(name)
showName()