---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2023/8/20 22:32
---

local currentPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")
dofile(currentPath .. "error 的文件.lua")