---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/10/31 08:45
---

print("------------------------")
print("加载字符串：")
do
    name = "江澎涌"
    local l, error = load("name = name..'。'")
    print("返回值", l, error)
    print(name)
    l()
    print(name)
    l()
    print(name)
end

print("------------------------")
print("加载函数：")
do
    local i = 0
    function loadContent()
        i = i + 1
        --print("in" .. i)
        if i == 1 then
            return "name"
        elseif i == 2 then
            return " = "
        elseif i == 3 then
            return "name.."
        elseif i == 4 then
            return "'.'"
        else
            -- 空字符串、 nil 、没有值表示结束
            --return ""
            --return nil
            return
        end
    end

    print("常规加载函数：")
    name = "江澎涌"
    local l, error = load(loadContent)
    print("返回值", l, error)
    print(name)
    l()
    print(name)
    l()
    print(name)

    print("全函数加载：")
    t = { name = "jiang" }
    local l1, error1 = load(loadContent, "jiangpengyong debug", "bt", t)
    print("返回值", l1, error1)
    print(t.name)
    l()
    print(t.name)
    l()
    print(t.name)
end

print("------------------------")
print("load 函数此法定界：")
do
    num = 10
    local num = 1

    local l, error = load("num = num + 1; print(num)")
    print(l, error)

    l()
    -- 打印局部的 num
    print(num)
    -- 打印全局的 num
    print(_G.num)
end

print("------------------------")
print("load 从文件中加载内容：")
do
    age = 28
    function showAge()
        print("main age", age)
    end

    --- local l, error = load(io.lines("/Users/jiangpengyong/Desktop/code/Lua/lua_study_2022/10 编译、执行和错误/编译/被搜索器加载的文件.lua"))
    --- 这样写会有问题，需要拆开
    local lines = io.lines("/Users/jiangpengyong/Desktop/code/Lua/lua_study_2022/10 编译、执行和错误/编译/被搜索器加载的文件.lua","L")
    local l, error = load(lines)
    print(l, error)
    l()

    print(name)
    showName()
end

print("------------------------")
print("load 副作用")
do
    local f = load("i=1")
    print(i)
    f()
    print(i)
end