---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2023/8/20 22:51
---

local currentPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")
local load, error = loadfile(currentPath .. "error 的文件.lua")
print(load, error)
load()