---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2023/8/21 09:11
---

print("------------------------")
print("load 异常的块")
do
    -- info 是 nil，load 加载块则会出异常
    local f = load("info.name")
    f()
end