---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/10/31 08:21
---

-- 此处不能用 local ，否则 loadfile 就无法使用
--local age = 28
age = 28
function showAge()
    print("main age", age)
end

local currentPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")
local load = loadfile(currentPath .. "加载的文件.lua")
print("---- 第一次调用 ----")
load()
print("---- 第二次调用 ----")
load()

print(name)
showName()