---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/17 17:49
---

function values(t)
    local i = 0
    return function()
        i = i + 1
        local v = t[i]
        if (v == nil) then
            return nil, nil
        else
            return i, v
        end
    end
end

t = { 10, 20, 30, 40, 50 }
for i, v in values(t) do
    print(i, "-----", v)
end