---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/9/25 14:58
---

print("Hello world.")

--print("jiang peng yong")

print("---------------")
print("递归：")
function fact(number)
    if number == 0 then
        return 1
    end
    return number * fact(number - 1)
end
print("Please enter a number:")
a = io.read("*n")
print(fact(a))