---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/10 17:00
---

local currentPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")

--- 添加 strict 模块
package.path = package.path .. ";" .. currentPath .. "?.lua"
require "strict"

name = "jiangpengyong"
print(name)

--- age 没有进行声明初始化，则运行会报错
--- age = nil
print(age)