---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/10 17:00
---

--- 添加 strict 模块
package.path = package.path .. ";/Users/jiangpengyong/Desktop/code/Lua/lua_study_2022/1 基础语法/?.lua"
require "strict"

name = "jiangpengyong"
print(name)

--- age 没有进行声明初始化，则运行会报错
--- age = nil
print(age )