---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/3 11:05 PM
---

print(4 and 5)
print(nil and 13)
print(false and 13)
print(0 or 5)
print(false or "hi")
print(nil or false)