---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/16 18:10
---

do
    local function basicSerialize(o)
        return string.format("%q", o)
    end

    function save(name, value, saved)
        saved = saved or {}
        io.write(name, " = ")
        if type(value) == "number" or type(value) == "string" then
            io.write(basicSerialize(value), "\n")
        elseif type(value) == "table" then
            if saved[value] then
                io.write(saved[value], "\n")
            else
                saved[value] = name
                io.write("{}\n")
                for k, v in pairs(value) do
                    print("v=", v)
                    k = basicSerialize(k)
                    local fname = string.format("%s[%s]", name, k)
                    save(fname, v, saved)
                end
            end
        else
            error("can't save a " .. type(value))
        end
    end
end

local table = {}
jiang = {}
xiao = {}
jiang[1] = xiao
xiao[1] = jiang
save("a", jiang, table)
for i, v in pairs(table) do
    print(i, "--", v)
end

print("")
a = { x = 1, y = 2, { 3, 4, 5 } }
a[2] = a
a.z = a[1]
save("a", a)

print("")
b = { { "one", "two" }, 3 }
c = { k = b[1] }
local t = {}
save("b", b, t)
save("c", c, t)
