---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/16 15:47
---

print("-------------------------")
print("统计个数：")
do
    local count = 0
    function Entry()
        count = count + 1
    end
    -- 内部会调用 entry
    local currentPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")
    dofile(currentPath .. "data.txt")
    print("number of entries: " .. count)
end

print("-------------------------")
print("收集数据：")
do
    local authors = {}
    function Entry(author)
        table.insert(authors, author)
    end
    -- 内部会调用 entry
    local currentPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")
    dofile(currentPath .. "data.txt")
    for key, author in pairs(authors) do
        print("key: ", key)
        for key, value in pairs(author) do
            print(key, "--", value)
        end
    end
end
