---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/12 18:29
---

do
    function unescape(s)
        s = string.gsub(s, "+", " ")
        return string.gsub(s, "%%(%x%x)", function(h)
            return string.char(tonumber(h, 16))
        end)
    end

    function decode(s)
        local cgi = {}
        for name, value in string.gmatch(s, "([^&=]+)=([^&=]+)") do
            name = unescape(name)
            value = unescape(value)
            cgi[name] = value
        end
        return cgi
    end
end

do
    function escape(s)
        return string.gsub(
                s,
                "[&=+%%%c]",
                function(c)
                    return string.format("%%%02X", string.byte(c))
                end) :gsub(" ", "+")
    end

    function encode(t)
        local b = {}
        for k, v in pairs(t) do
            b[#b + 1] = (escape(k) .. "=" .. escape(v))
        end
        return table.concat(b, "&")
    end
end

t = { name = "al", query = "a+b = c", q = "yes or no" }
e = encode(t)
d = decode(e)
print(e)
for i, v in pairs(d) do
    print(i, "-->", v)
end
