---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/14 09:28
---

do
    -- 组建匹配规则
    local pattern = string.rep("[^\n]", 70) .. "+"
    print(pattern)
end

do
    -- 对双引号内容进行大写操作，\x 的会进行先转义后再转回来
    function code(s)
        return string.gsub(s, "\\(.)", function(x)
            return string.format("\\%03d", string.byte(x))
        end)
    end

    function decode(s)
        return string.gsub(s, "\\(%d%d%d)", function(d)
            return "\\" .. string.char(tonumber(d))
        end)
    end

    s = [[follows a typical string: "This is \"great\"!".]]
    print(string.gsub(s, '".-"', string.upper))
    s = code(s)
    s = string.gsub(s, '".-"', string.upper)
    s = decode(s)
    print(s)
end