---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/12 17:20
---

do
    -- _G 全局变量表
    function expand(s)
        return (string.gsub(s, "$(%w+)", _G))
    end

    name = "Lua"
    status = "great"
    print(expand("$name is $status"))

    function toXML(s)
        s = string.gsub(s, "\\(%a+)(%b{})", function(tag, body)
            print(tag, body)
            body = string.sub(body, 2, -2)
            body = toXML(body)
            return string.format("<%s>%s</%s>", tag, body, tag)
        end)
        return s
    end
    print(toXML("\\title{The \\bold{big} example}"))
end

