---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/11 16:55
---

s1 = "hello world"
s2 = "a [world]"

date = "Today is 12/04/2022"
do
    -- string.find
    local i, j = string.find(s1, "hello")
    print(i, j)
    print(string.sub(s1, i, j))
    print(string.sub(s1, s1:find("world")))

    -- 因为 [ 是特殊字符，所以需要强制开启简单搜索模式
    --print(s2:find("["))
    print(s2:find("[", 1, true))

    print(date:sub(date:find("%d+/%d+/%d+")))

    -- %a* 可以匹配 0-n 字母，会匹配到开头的空字符串
    print(string.find(";$%  **#$hello13", "%a*"))
end

do
    print("")
    -- string.match
    print(s1:match("hello"))

    local data = date:match("%d+/%d+/%d+")
    print(data)
end

do
    print("")
    -- string.gsub
    print(string.gsub("Lua is cute", "cute", "great"))
    print(string.gsub("jiang peng yong", "n", "0"))
    -- 只替换一次
    print(string.gsub("jiang peng yong", "n", "0", 1))
    -- 只替换两次
    print(string.gsub("jiang peng yong", "n", "0", 2))
end

do
    print("")
    -- string.gmatch
    s = "some thing"
    words = {}
    for w in string.gmatch(s, "%a+") do
        words[#words + 1] = w
    end
    for i, v in ipairs(words) do
        print(i, "-->", v)
    end
end

do
    -- 修饰符
    print(string.gsub("one, and two; and three", "%a+", "word"))
    print(string.gsub("one, and two; and three", "%a-", "word"))
    print(string.match("the number 1024.", "%d+"))
end

do
    -- 字符
    print(string.gsub("a (enclosed (in) parentheses) line", " %b() ", " "))
    s = "the anthem is the theme"
    -- %f[%w]the%f[%W] 这样只能完整匹配 "the" , "anthem" 和 "theme" 的 "the" 则不会
    print(string.gsub(s, "%f[%w]the%f[%W]", "one"))
    print(string.gsub(s, "the", "one"))
end

do
    -- 捕获
    pair = "name = jiang"
    key, value = string.match(pair, "(%a+)%s*=%s*(%a+)")
    print(key, value)

    date = "Today is 12/04/1994"
    day, month, year = date:match("(%d+)/(%d+)/(%d+)")
    print(year, month, day)

    s = [[then he said: "it's all right"]]
    print(s:match("[\"'].-[\"']"))
    print(s:match("([\"'])(.-)%1"))
    print(s:match("(%s+)([%a])(.-)%2"))

    s = "Hello Lua!"
    print(s:gsub("%a", "%0-%0"))
    print(s:gsub("%a", "%1-%1"))
    print(s:gsub("(.)(.)", "%2%1"))
    print(s:gsub("(.)(.)(.)", "%0 - %2"))
    print(s:gsub("(.).(.)", "%0 - "))

    -- \command{some text} --> <command>some text</command>
    s = [[the \quote{task} is to \em{change} that.]]
    print(s)
    print(string.gsub(s, "\\(%a+){(.-)}", "<%1>%2</%1>"))

    function trim(s)
        return string.gsub(s, "^%s*(.-)%s*$", "%1")
    end
    print(trim("  jiang pengyong     "))

    print(string.match("helo ill", "()ll()"))

    function expandTabs(s, tab)
        tab = tab or 8
        local corr = 0
        return string.gsub(s, "()\t", function(p)
            local sp = tab - (p - 1 + corr) % tab
            corr = corr - 1 + sp
            return string.rep(" ", sp)
        end)
    end
    print("Hello\tjiang pengyong")
    print(expandTabs("Hello\tjiang pengyong"))
end