---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/21 09:22
---

print("================================================")
print("设置析构器：")
do
    local o = { name = "江澎涌" }
    setmetatable(o, { __gc = function(o)
        print("o gc", o.name)
    end })
    o = nil
    collectgarbage()
end

print("================================================")
print("析构器必须要在设置元表的一开始就设置了，可以先占坑，后再真正设置函数：")
do
    local info = { name = "江澎涌" }
    local mt = {
        -- 一定要先占坑，否则后续加的 __gc 会无效
        __gc = true
    }
    setmetatable(info, mt)
    mt. __gc = function(o)
        print("info gc", o.name)
    end
    info = nil
    collectgarbage()
end

print("================================================")
print("析构顺序：")
do
    local mt = { __gc = function(o)
        print(o[1])
    end }
    local list = nil
    for i = 1, 3 do
        list = setmetatable({ i, link = list }, mt)
    end
    list = nil
    collectgarbage()
end

print("================================================")
print("复苏对象：")
do
    local user = { name = "小朋友" }
    local mt = {
        __gc = function(o)
            print("user gc", o.name)
            user1 = o
        end
    }
    setmetatable(user, mt)
    print(user)
    user = nil
    collectgarbage()

    print(user1.name)
    print(user1)
    setmetatable(user1, mt)
    collectgarbage()
end