---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/21 12:51 PM
---

do
    local mt = {
        __gc = function(o)
            print("new cycle", o)
            setmetatable({}, getmetatable(o))
        end
    }
    setmetatable({}, mt)
end

--local mt = {
--    __gc = function()
--        print("finishing Lua Program.")
--    end
--}
--setmetatable(mt, mt)
--_G[{}] = mt

print("---- 1 -----")
collectgarbage()
print("---- 2 -----")
collectgarbage()
print("---- 3 -----")
collectgarbage()
print("---- 4 -----")
collectgarbage()
print("---- 5 -----")
collectgarbage()

print("---- 结束 -----")