---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/20 9:41 PM
---

print("=================================================")
print("默认值——全部使用同一元表：")
do
    local defaults = {}
    setmetatable(defaults, { __mode = "k" })
    local mt = { __index = function(table)
        return defaults[table]
    end }
    local function setDefault(table, default)
        defaults[table] = default
        setmetatable(table, mt)
    end

    local t = { x = 10, y = "江" }
    print(t.x, t.y, t.z)
    setDefault(t, "default value")
    print(t.x, t.y, t.z)
end

print("=================================================")
print("默认值——默认值共享元表：")
do
    local metas = {}
    setmetatable(metas, { __mode = "v" })
    local function setDefault(table, default)
        local mt = metas[default]
        if mt == nil then
            mt = { __index = function()
                return default
            end }
            metas[default] = mt
        end
        setmetatable(table, mt)
    end

    local t = { x = 10, y = "江" }
    print(t.x, t.y, t.z)
    setDefault(t, "default value")
    print(t.x, t.y, t.z)
end