---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/21 12:49 PM
---

local mt = {
    __gc = function()
        print("finishing Lua Program.")
    end
}
setmetatable(mt, mt)
_G["*AA*"] = mt

--setmetatable(_G, mt)