---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/20 8:41 PM
---

a = {}
mt = { __mode = "k" }
setmetatable(a, mt)
k1 = {}
a[k1] = 10
k2 = {}
a[k2] = 20

-- 删除值
k1 = nil
-- 垃圾回收
collectgarbage()
for i, v in pairs(a) do
    print(i, v)
end