---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/21 09:22
---

o = { name = "江澎涌" }
setmetatable(o, { __gc = function(o)
    print("o gc", o.name)
end })
o = nil

info = { name = "江澎涌" }
mt = {
    -- 一定要先占坑，否则后续加的 __gc 会无效
    __gc = true
}
setmetatable(info, mt)
mt. __gc = function(o)
    print("info gc", o.name)
end
mt = nil
collectgarbage()