---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/16 14:12
---

function listNew()
    return { first = 0, last = -1 }
end

function pushFirst(list, value)
    local first = list.first - 1
    list.first = first
    list[first] = value
end
