---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/6 12:49 PM
---

-- 等同于 print("function")
print "function"
-- 等同于 dofile("字符串.lua")
--dofile "字符串.lua"
-- 等同于 type({})
print(type {})

globalCounter = 0;
function initGlobal(n)
    n = n or 1
    globalCounter = globalCounter + n;
end
initGlobal()
print(globalCounter)
initGlobal(10086)
print(globalCounter)
