---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/4 3:00 PM
---

-- integer 和 float
print("\n")
print(math.type(3))
print(math.type(3.0))
print(type(3))
print(type(3.0))

-- 十六进制浮点数
print("\n")
print(0x0.2)
print(0x1p-1)
--print(0xa.bp2)

-- 十六进制浮点数输出
print("\n")
print(string.format("%a", 419))
print(string.format("%a", 0.1))

-- 数值除法
print("\n")
print(3 / 2)
print(3.0 / 2.0)

-- float 除法 运算符
print("\n")
print(3 // 2)
print(3.0 // 2)
print(6 // 2)
print(6.0 // 2.0)
print(-9 // 2)
print(1.5 // 0.5)

-- 取模
print("\n")
print(3 % 2)
print(3.0 % 2)
print(-15 % 2)
print(3.1415926 % 0.01)

-- 最大值
print("\n")
print(math.huge)

-- 三角函数
print("\n")
print(math.deg(6.2831853071796))
print(math.rad(360))