---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/11/15 10:21
---

function readOnly(t)
    local proxy = {}

    local metatable = {
        __index = t,
        __newindex = function(t, k, v)
            error(string.format("attempt to update a read-only table.[%s]:[%s]", k, v), 2)
        end
    }

    setmetatable(proxy, metatable)

    return proxy
end

local days = { 1, 2, 3, 4, 5, 6 }
print(days[5])
day[5] = 55