---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/11/15 09:45
---

function track(t)
    local proxy = {}

    local metatable = {
        __index = function(_, k)
            print(string.format("access to element [%s]", tostring(k)))
            return t[k]
        end,
        __newindex = function(_, k, v)
            print(string.format("update of element [%s] to [%s]", tostring(k), tostring(v)))
            t[k] = v
        end,
        __pairs = function()
            -- 返回 迭代函数，不可变状态，控制变量
            -- 参数为 不可变状态，控制变量
            -- 函数为 迭代函数
            return function(_, k)
                local nextkey, nextvalue = next(t, k)
                if nextkey ~= nil then
                    print(string.format("traversing element [%s]", tostring(nextkey)))
                end
                return nextkey, nextvalue
            end
        end,
        __len = function()
            return #t
        end
    }

    setmetatable(proxy, metatable)

    return proxy
end

print("=======================================")
print("代理：")
local t = {}
print("原始 table", t)
t = track(t)
print("跟踪后的 table", t)
print("---------------------------------------")
print("设置值：")
t["name"] = "jiang pengyong"
t["age"] = 29
t[1] = "100"

print("---------------------------------------")
print("获取值：")
print(t["name"])
print(t[1])

print("---------------------------------------")
print("遍历")
for key, value in pairs(t) do
    print(key, value)
end

print("---------------------------------------")
print("长度")
print("#t", #t)