---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/14 14:11
---

do
    t = os.date("*t")
    for k, v in pairs(t) do
        print(k, "=", v)
    end
end

do
    print("")
    print("%a 星期简称", os.date("%a"))
    print("%A 星期全称", os.date("%A"))
    print("%b 月份简写", os.date("%b"))
    print("%B 月份全名", os.date("%B"))
    print("%c 日期和时间", os.date("%c"))
    print("%d 一个月中的第几天", os.date("%d"))
    print("%H 24 小时制", os.date("%H"))
    print("%I 12 小时制", os.date("%I"))
    print("%j 一年中的第几天", os.date("%j"))
    print("%m 月份", os.date("%m"))
    print("%M 分钟", os.date("%M"))
    print("%p am 或 pm", os.date("%p"))
    print("%S 秒数", os.date("%S"))
    print("%w 星期", os.date("%w"))
    print("%W 一年中的第几周", os.date("%W"))
    print("%x 日期", os.date("%x"))
    print("%X 时间", os.date("%X"))
    print("%y 两位数的年份", os.date("%y"))
    print("%Y 完整的年份", os.date("%Y"))
    print("%z 时区", os.date("%z"))
    print("%% 百分号", os.date("%%"))
end

do
    print("")
    timestamp = os.time()
    print(os.date("%Y-%m-%d", timestamp))
    print(os.date("%Y-%m-%dT%H:%M:%S", timestamp))
    print(os.date("%Y-%j", timestamp))
    print(os.date("%c", timestamp))
    -- UTC
    print(os.date("!%c", timestamp))
    -- 第一个参数默认 %c , 第二个参数默认当前时间
    print(os.date())
end

do
    print("")
    local timestamp = os.time()
    print(timestamp)
    print(os.date("%Y/%m/%d", timestamp))
    local currentTable = os.date("*t", timestamp)
    -- 向前推 40 天
    currentTable.day = currentTable.day - 40
    print(os.date("%Y/%m/%d", os.time(currentTable)))
    -- 向后 6 个月
    currentTable = os.date("*t", timestamp)
    currentTable.month = currentTable.month + 6
    print(os.date("%Y/%m/%d", os.time(currentTable)))

    -- 这里的转换会有问题（由于日历机制导致）
    -- 3 月 31 号 + 1 个月 --> 4 月 31 号 --> 5 月 1 号
    -- 5 月 1 号 - 1 个月 --> 4 月 1 号
    local t = { year = 2022, month = 3, day = 31 }
    print(os.date("%Y-%m-%d", os.time(t)))
    t.month = t.month + 1
    print(os.date("%Y-%m-%d", os.time(t)))
    t.month = t.month - 1
    print(os.date("%Y-%m-%d", os.time(t)))
end

do
    -- 计算时间差值
    print("")
    local start = os.time({ year = 2022, month = 1, day = 1 })
    local current = os.time()
    local diff = os.difftime(current, start)
    print(diff)
    local t = { year = 2023, month = 1, day = 1 }
    print(os.time(t))
    t.sec = diff
    print(os.time(t))
    print(os.date("%Y/%m/%d", os.time(t)))
end
