---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/14 14:11
---

-- 时间戳
print(os.time())

-- 自行转换
do
    local day2year = 365.242
    local sec2hour = 60 * 60
    local sec2day = sec2hour * 24
    local sec2year = sec2day * day2year
    function getYear(timestamp)
        -- 时间戳是从 Jan 01,1970,0:00 UTC 开始
        return timestamp // sec2year + 1970
    end
    function getHour(timestamp)
        return timestamp % sec2day // sec2hour
    end
    function getMinute(timestamp)
        return timestamp % sec2hour // 60
    end
    function getSecond(timestamp)
        return timestamp % 60
    end
end

print("--------------------")
print("解析时间戳：")
-- 1665536638 --> 北京时间 2022-10-12 09:03:58
local timestamp = 1665536638
print("timestamp", timestamp)
print("year", getYear(timestamp))
print("hour", getHour(timestamp))
print("minute", getMinute(timestamp))
print("second", getSecond(timestamp))

print("--------------------")
print("日期表：")
local timeTable = {
    -- 必填项 year、month、day
    year = 2022,
    month = 4,
    day = 14,
    -- 选填项 hour、minute、second，不填默认为 12:00:00
    hour = 13,
    min = 10,
    sec = 10,
    -- 选填项 isdst，默认为 nil
    isdst = false
    -- wday、yday 填了也会被忽略
}
print("isdst = false", os.time(timeTable))

timeTable.isdst = true
print("isdst = true", os.time(timeTable))

print(os.time({ year = 1970, month = 1, day = 1, hour = 24 * 5 }))
