---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/20 8:04 PM
---

print("====================================================")
print("给 loadfile 传入上值，放置外部全局被改动：")
do
    name = "江澎涌"
    local env = { print = print }
    local l = loadfile("/Users/jiangpengyong/Desktop/study/lua_study_2022/15 环境/模块隔离/被加载的 config .lua", "t", env)
    l()
    print(env.width, env.height)
    print("外部全局 name ：", name)
    print("加载的模块的 name ：", env.name)

    print("修改 loadfile 已使用的上值：")
    env["name"] = "jiang pengyong"
    l()
    print(env.width, env.height)
    print("外部全局 name ：", name)
    print("加载的模块的 name ：", env.name)
end

print("====================================================")
print("给 load 传入上值：")
do
    local env = {}
    f = load([[
    width = 200
    height = 200
    name = "将 name 进行篡改 via load"
    ]], "load test", "t", env)
    f()
    print(env.width, env.height)
    print("外部全局 name ：", name)
    print("加载的模块的 name ：", env.name)
end

print("====================================================")
print("通过 debug.setupvalue 更改函数上值：")
do
    age = "29"
    height = 200
    local f = load("age = 20; return height;")
    -- 更改 f 的上值
    local env = { height = 20 }
    debug.setupvalue(f, 1, env)

    print(f())
    print(env.age, env.height)
    print(age, height)

    local changeAge = function()
        age = 19
    end
    local env = { age = age }
    debug.setupvalue(changeAge, 2, env)
    changeAge()
    print(age)
    print(env.age)
end