---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/4/20 8:04 PM
---

print("====================================================")
print("给 loadfile 传入上值，放置外部全局被改动：")
do
    name = "江澎涌"
    local env = { print = print }
    local currentPath = debug.getinfo(1, "S").source:sub(2):match("(.*/)")
    local l = loadfile(currentPath .. "被加载的 config .lua", "t", env)
    l()
    print(env.width, env.height)
    print("外部全局 name ：", name)
    print("加载的模块的 name ：", env.name)

    print("修改 loadfile 已使用的上值：")
    env["name"] = "jiang pengyong"
    l()
    print(env.width, env.height)
    print("外部全局 name ：", name)
    print("加载的模块的 name ：", env.name)
end

print("====================================================")
print("给 load 传入上值：")
do
    local env = {}
    f = load([[
    width = 200
    height = 200
    name = "将 name 进行篡改 via load"
    ]], "load test", "t", env)
    f()
    print(env.width, env.height)
    print("外部全局 name ：", name)
    print("加载的模块的 name ：", env.name)
end

print("====================================================")
print("通过 debug.setupvalue 更改函数上值：")
do
    age = "29"
    height = 1000
    local f = load("age = 20; return height;")
    local env = { height = 50 }

    print("未更改 f 的上值")
    print(f())
    print(env.age, env.height)
    print(age, height)

    print("更改 f 的上值")
    debug.setupvalue(f, 1, env)
    print(f())
    print(env.age, env.height)
    print(age, height)
end

do
    age = 29
    local changeAge = function()
        print(age)
    end
    print("未更改 changeAge 上值")
    changeAge()

    print("更改 changeAge 上值")
    local env = { age = 100, print = print }
    debug.setupvalue(changeAge, 1, env)
    changeAge()
end